pipeline:
  name: allure-pytest-github
  identifier: Build_cheshi_mantu_allure_pytest_github_1711475531568
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: get allurectl
                  identifier: get_allurectl
                  spec:
                    shell: Sh
                    command: |-
                      wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
                      chmod +x allurectl
                      ./allurectl --version
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: cheshi-mantu/allure-pytest-github
        build: <+input>
